version: '2'

services:

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - mysql

  app:
    image: php
    build: docker/php-fpm
    container_name: php-fpm
    volumes:
      - ./:/var/www
      - ~/.composer:/root/.composer
    ports:
      - 9000:9000
    depends_on:
      - mysql